### ISSUE TITLE
puppeteer newPage hangs/freeze, headless mode issue

### ISSUE THREAD

**Issue by towry** [towry/n#148]
The library that I use: pyppeteer

Two issues:

1. The Chromium that bundled with pyppeteer has newPage freeze issue, see [google search of newPage freeze](https://www.google.com/search?q=newPage+freeze&oq=newPage+freeze&aqs=chrome..69i57j0i5i10i30j69i61l2.3295j1j7&sourceid=chrome&ie=UTF-8), it seems is the bug of glibc.
2. If I use the latest Chrome, the freeze issue is gone, but the [stealth plugin](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) wont' work, because the latest Chrome/Chromium have fixed an issue related to the `navigator.webdriver`. So, we can not delete the `navigator.webdriver` property in latest Chrome.

The solution:

Use this version: https://chromium.cypress.io/linux/stable/84.0.4147.89

**Comment by nowgoo** [comment]
you saved my life, bro.  👍
